version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"   # from the good config
    open-pull-requests-limit: 99
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns: ["*"]
        update-types: ["patch", "minor"]
      prod-dependencies:
        dependency-type: "production"
        patterns: ["*"]
        update-types: ["patch", "minor"]

